version: '3'

volumes:
  local-data:
  ftp-location:
    driver: valuya/curlftpfs:next # NOTE make sure you have the driver plugin installed: docker plugin install valuya/curlftpfs:next DEBUG=1
    driver_opts:
      address: ftp://tgftp.nws.noaa.gov/data/tampa/

services:
  consumer: 
    image: httpd
    container_name: ftp-data-consumer
    ports:
      - 8001:80
    volumes:
      - local-data:/usr/local/apache2/htdocs/data
  cron:
    image: arcaneio/docker-cron
    container_name: test-data-sync
    environment: 
      CRON_RSYNC: "*/5 * * * * rsync -rzvt --inplace --update --progress --stats /opt/ftp-data/ /opt/synchronized-data"
    volumes:
      - ftp-location:/opt/ftp-data
      - local-data:/opt/synchronized-data
