version: '3'

services:
  cron:
    image: arcaneio/crontab
    container_name: arcaneio-cron-example
    environment: 
      CRON_SAMPLE: '* * * * * echo 1 minute cron'
      CRON_ANOTHER_SAMPLE: '*/5 * * * * echo 5 minute cron'
      CRON_ERROR_SAMPLE: '*/3 * * * * no-valid-command'